const prod = [
    {   title:"alumina lamp charcoal",
        price:195,
        img:"/img/products/alumina-lamp-charcoal",//in src need to put {this path-(lg/md/sm)-(hover ? hover}.format
        format:".jpg",
        hover:true,
    },
    {title:"desk tray (dark/large)",
        price:150,
        img:"/img/products/cork-desk-tray-dark-large",
        format:".jpg",
        hover:false,
    },
    {title:"walnut desk shelf",
        price:100,
        img:"/img/products/desk-shelf-walnut",
        format:".jpg",
        hover:true,
    },
    {title:"desk pad (black)",
        price:180,
        img:"/img/products/forbo-desk-pad-black",
        format:".jpg",
        hover:true,
    },
    {title:"walnut keyboard tray",
        price:140,
        img:"/img/products/keyboard-tray-medium-walnut",
        format:".jpg",
        hover:false,
    },
    {title:"black minimalist wallet",
        price:100,
        img:"/img/products/minimalist-wallet-black",
        format:".jpg",
        hover:true,
    },
    {title:"walnut&leather mouse pad",
        price:60,
        img:"/img/products/mouse-pad-leather-walnut",
        format:".jpg",
        hover:true,
    },
    {title:"studio pad (wool/dark)",
        price:1000,
        img:"/img/products/studio-pad-wool-dark-medium",
        format:".jpg",
        hover:true,

    },
    {title:"black task knife",
        price:70,
        img:"/img/products/task-knife-black",
        format:".jpg",
        hover:false,
    },
    {title:"walnut monitor stand",
        price:160,
        img:"/img/products/walnut-desk-collection-monitor-stand",
        format:".jpg",
        hover:true,
    },
    {title:"walnut headphone stand",
        price:80,
        img:"/img/products/walnut-headphone-stand",
        format:".jpg",
        hover:true,
    },
    {title:"walnut ipad stand",
        price:140,
        img:"/img/products/walnut-ipad-stand",
        format:".jpg",
        hover:true,
    },
    {title:"walnut laptop riser",
        price:150,
        img:"/img/products/walnut-laptop-riser",
        format:".jpg",
        hover:true,
    },
    {title:"walnut magsafe dock lg",
        price:2200,
        img:"/img/products/walnut-magsafe-dock",
        format:".jpg",
        hover:true,
    },
    ];

    export default prod;